services:
  age:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    image: "docker.io/apache/age:release_PG16_1.5.0"
    command:
      - postgres
      - -c
      - shared_buffers=1GB
      - -c
      - maintenance_work_mem=512MB
    volumes:
      - ./db-data:/var/lib/postgresql/data:z
    ports:
      - "5433:5432"
