version: '3'
services:
  age:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    image: "docker.io/apache/age:PG16_latest"
    ports:
      - "5433:5432"
